### ISSUE TITLE
Drive mounted, but don't see list of games

### ISSUE THREAD

**Issue by Kunal-Joshi** [vKolerts/quest-sidenoder#1]
<img width="1198" alt="Screenshot 2021-06-23 at 7 28 59 AM" src="https://user-images.githubusercontent.com/13332105/123023368-e442dc00-d3f4-11eb-9932-46f4d277eed3.png">

Tried all mirrors, any fix for this?

**Comment by michel130** [comment]
Same problem,
Could not found the mount drive.
In my case it is under windows 10.

**Comment by vKolerts** [comment]
Can you start application by console and give me a log?

**Comment by Horus83** [comment]
Same for me, "Mount status connected" but when click "Click to browse mount" nothing happens...and no error in Console...how I can fix?

**Comment by michel130** [comment]
I read:
JUNE 18 2021 : NOTICE: OFFICIAL SIDENODER DISCONTINUED
There is no log file on my site:  
Only  Trying to fetch device storage info 
So it is trying to connect to a storage somewhere.

**Comment by vKolerts** [comment]
> ONLOAD
> index.twig:317 setup ask device listener
> index.twig:344 ONLOAD INDEX
> index.twig:345 sending check_deps
> index.twig:237 get_device msg came FROM BE to fe:
> index.twig:238 Object
> index.twig:210 check_mount
> ...
Not this console log. If you use windows, then start app by cmd.exe

**Comment by vKolerts** [comment]
Catched the problem. Need of killing rclone
Will add fix at next release. At this time you can kill rclone manualy

**Comment by JulienMaille** [comment]
I still have this issue with latest release. Sidenoder mounts `C:/Users/julien/AppData/Local/Temp/mnt` which is empty
