### ISSUE TITLE
Replace packagename with notes

### ISSUE THREAD

**Issue by pmow** [vKolerts/quest-sidenoder#12]
**Is your feature request related to a problem? Please describe.**
Users cannot view notes included in VRP uploads.  For example Game Title v123 (includes BMBF).

**Describe the solution you'd like**
Rather than display the packagename, which nobody really needs, maybe this is a good place to include the optional note.

**Describe alternatives you've considered**
Clicking on the game to view the APK file will also show the relevant information.

![image](https://user-images.githubusercontent.com/826297/125535733-87aa347a-48c6-484f-90f3-b010c0a66a50.png)

**Comment by vKolerts** [comment]
Package name is very helpfull for me. And anyway, for example Beat Saber v157+1.13.2 -QU (manual install, see notes) contain more than one short line: ```
Make sure to delete ALL beatsaber/bmbf/beastsaber files first. 

Install "Beat_Saber_ [1.13.2.157] + DLC_Unlocker_S3.0.2" and run it

Install latest BMBF https://bmbf.dev/stable

Patch Beat Saber with BMBF. STOP when it asks you to install the patched APK

Take off headset and install the APK from "Beat_Saber_ [1.13.2.157] + BMBF + DLC_S3.0.2"

Return to headset and complete the BMBF installation by pressing the install modded beatsaber button

Delete the OBB folder com.beatgames.beatsaber from \ Android \ OBB

Manually install the OBB folder from "Beat_Saber_ [1.13.2.157] + BMBF + DLC_S3.0.2"

Exit beatsaber and BMBF

Launch BMBF goto playlist tab and press sync to quest button

Launch BeatSaber 🙂
```
It can't fit at this place

I will think how to adding notes, maybe as hover text

**Comment by vKolerts** [comment]
at next release I will include note from brackets to title name(I think you meant it, not notes.txt)
![изображение](https://user-images.githubusercontent.com/69972136/125593582-d9a5c7ad-8ef7-4846-aa35-5a6280aa7884.png)
