### ISSUE TITLE
Error on Mount

### ISSUE THREAD

**Issue by Horus83** [vKolerts/quest-sidenoder#14]
When I try to Mount disk this give me an error (see image).
Another error is when I can mount the disk correctly no change the path in 'Browse' label
![error](https://user-images.githubusercontent.com/86409932/126895566-dfb8606e-886b-45d2-86e0-75fae0e6bc39.png)

**Comment by vKolerts** [comment]
will be fixed at next release

**Comment by vKolerts** [comment]
please try 0.5.2
