### ISSUE TITLE
Can't find 7zip Archiver

### ISSUE THREAD

**Issue by Horus83** [vKolerts/quest-sidenoder#15]
At start in "System check" say me:
 Can't find 7zip Archiver - try to manualy download latest  and set custom location at settings
error: 
Error: Command failed: C:\Users\darkt\sidenoder\7za.exe --help | findstr  "Version"

But file in "C:\Users\darkt\sidenoder\7za.exe" exist...(see image)
Thanks
![error](https://user-images.githubusercontent.com/86409932/126905678-9f926686-53b5-4385-aad2-65b8264029db.png)

**Comment by vKolerts** [comment]
Thanks for report, I will  inspect that
Don't worry, at this version it not required
