### ISSUE TITLE
Error during browsing local folders

### ISSUE THREAD

**Issue by jenya** [vKolerts/quest-sidenoder#16]
**Describe the bug**
Impossible to browse local directories. 
Seems there is a bug during compiling directory path ` C:/Usersjenya/sidenoder` instead of ` C:/Users/jenya/sidenoder` (slash missed)

**To Reproduce**
1. Go to 'Browse'
2. Click on any directory
3. See error: `ERROR: Browse failed`

**Expected behavior**
Be able to browse directories

**Desktop (please complete the following information):**
 - OS: windows 10
 - Versions: 0.5.0-0.5.2

**Log**
```
taskkill.exe /F /IM rclone.exe /T stdout: SUCCESS: The process with PID 129292 (child process of PID 28456) has been terminated.

start rclone
checkMount()
get_dir received
get_dir received
get_dir received C:/Usersjenya/sidenoder
ERROR: Can`t open folder C:/Usersjenya/sidenoder [Error: ENOENT: no such file or directory, scandir 'C:\Usersjenya\sidenoder'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Usersjenya\\sidenoder'
}
close
```

**Comment by vKolerts** [comment]
Thank`s for report, I will check

**Comment by vKolerts** [comment]
Catched it. Will fixed. At this time you can open remote and double go up folder
