### ISSUE TITLE
Mount Problem Mac

### ISSUE THREAD

**Issue by Mqdboi** [vKolerts/quest-sidenoder#19]
![Screen Shot 2021-08-05 at 6 54 45 PM](https://user-images.githubusercontent.com/82172863/128444229-fe77f14a-9887-4984-b4bf-458adf4acec8.png)

**Comment by vKolerts** [comment]
The text doesn't look like an error. Did you attempt to remount?

**Comment by Mqdboi** [comment]
Yeah, didn't know how to access the mount so I assumed just to click it again, figured it out thanks.

**Comment by bellalau** [comment]
I'm seeing the same prompt. I run the previous version with NPM and downloaded sidenoder 2. The NPM ver mounts perfectly. Is there any way to update the new ver through NPM?

**Comment by TacoB3ll** [comment]
I'm having the same issue on ver 2. I run ver 1 through NPM and it mounts perfectly. Is there a way to update to ver 2 through NPM? I tried npm update but to no avail.
