### ISSUE TITLE
Game info shows Gb instead of Mb

### ISSUE THREAD

**Issue by edubox** [vKolerts/quest-sidenoder#24]
**Describe the bug**

In the game list, the size of the game shows Gb instead of Mb (or the number showed should be converted to Gb)

**To Reproduce**
Just list games

**Expected behavior**
Should show the correct Mb or Gb

**Screenshots**
[https://i.imgur.com/ESMl06y.png](url)

**Desktop (please complete the following information):**
 - OS: Windows with version 0.6.0

**Comment by kalkih** [comment]
Seems to be fixed in the `dev` branch already, see https://github.com/vKolerts/quest-sidenoder/commit/ade7d38fe3845b1bf2d25a21b1660451e80c6805.
