### ISSUE TITLE
Trouble Re-Installing Rclone

### ISSUE THREAD

**Issue by Mqdboi** [vKolerts/quest-sidenoder#27]
I was messing around with storage and accidentally deleted Rclone, and now I have no idea how to re-install it, Ive tried putting it back in my sidenoder folder and re-installing it but I get an error that I don't know how to fix, help would be appreciated! 
![Screen Shot 2021-09-11 at 3 56 13 PM](https://user-images.githubusercontent.com/82172863/132963599-45ddcbd4-dc61-4ebb-b4a0-7a79470ee611.png)

**Comment by vKolerts** [comment]
Delete it and restart sidenoder. Rclone will be downloaded automatically
