### ISSUE TITLE
Error when opening side loiader

### ISSUE THREAD

**Issue by SouthsideAllstar** [vKolerts/quest-sidenoder#3]
Hi all, pretty new to all this.

I am trying to install Sidenoder and everything installs as I believe it should using terminal and says homebrew installed etc but when I then open sidenoder I get "ADB global installation not found, please read the README on github.

any help would be greatly appreciated. I am on Mac also btw

**Comment by vKolerts** [comment]
Please give me a output of command ```brew install android-platform-tools```

**Comment by macuser2993234** [comment]
no devices found im having same issue

**Comment by macuser2993234** [comment]
my bad command not found

**Comment by vKolerts** [comment]
installing for mac updated at readme. Please close issue if new guide help you
