### ISSUE TITLE
Games only bunch of empty folder

### ISSUE THREAD

**Issue by rhyolitedv** [vKolerts/quest-sidenoder#40]
<img width="1428" alt="Screen Shot 2021-12-23 at 19 29 14" src="https://user-images.githubusercontent.com/96575518/147240800-c99f4cbe-f8c6-4000-8f3d-f184cfb1d642.png">
**Describe the bug**
There's nothin in the game files.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Running via binary or npm start
 - Version [e.g. v0.0.3-alpa]

**Additional context**

**Comment by vKolerts** [comment]
You can attempt to change mirror. Actual mirrors you can get there http://t.me/sidenoder
