### ISSUE TITLE
PCVR Games

### ISSUE THREAD

**Issue by fake-r** [vKolerts/quest-sidenoder#6]
**Describe the bug**
When I open the PCVR games, I can see the games there but there's no option to copy the folder and when I open the games folder there's nothing in there but when I check the size it shows in some GB amount

**Screenshots**

![Screenshot from 2021-06-30 05-14-45](https://user-images.githubusercontent.com/46718370/123881380-26729d00-d962-11eb-9057-ce81d3833212.png)
![Screenshot from 2021-06-30 05-14-51](https://user-images.githubusercontent.com/46718370/123881382-27a3ca00-d962-11eb-9526-2a3fd71f610f.png)

**Desktop**
 - OS: Linux Ubuntu
 - Running via npm start

**Comment by vKolerts** [comment]
download option planed at one of next release
