### ISSUE TITLE
ADB global installation not found, please read the README on github.

### ISSUE THREAD

**Issue by michel130** [vKolerts/quest-sidenoder#7]
**Describe the bug**

I download sidenoder-0.2.2-win.zip and extract it on my windows 10 desktop.

I run the windows-install.bat

After than I received that everything is okay and I can start SideNoder application,

SUCCESS: Specified value was saved.
Dependencies installed.
You can start SideNoder application
Press any key to continue . . .

![image](https://user-images.githubusercontent.com/26072664/124006732-e8658f80-d9da-11eb-8bc8-b82107656bf9.png)

See error 

**Desktop (please complete the following information):**
 - Windows
 - Running via binary or npm start
 - Version [e.g. v0.22]

I am complete lost why this program will not start.

**Comment by vKolerts** [comment]
Please try ```adb devices``` command from cmd.exe

**Comment by vKolerts** [comment]
Now adb not need install separetly
Try version 0.3.0
