### ISSUE TITLE
remote tab not showing game list plus only vrpe 9 mount works

### ISSUE THREAD

**Issue by macuser2993234** [vKolerts/quest-sidenoder#8]
Im mac big sur m1 chip ive done everything install osxfuse macfuse and nothing works ![image](https://user-images.githubusercontent.com/86694018/124007514-49b44100-d990-11eb-9fb2-e5752bb78694.jpeg)![image](https://user-images.githubusercontent.com/86694018/124007515-49b44100-d990-11eb-936c-e352d7f577ce.jpeg)

**Comment by snitch1919** [comment]
exactly same

**Comment by vKolerts** [comment]
I think, rclone from brew - it doesn`t support mount function. Please try remove brew version of rclone & install by this command ``` curl https://rclone.org/install.sh | sudo bash``` Please write me to telegram https://t.me/vKolerts

**Comment by vKolerts** [comment]
please try version 0.3.0
download manualy latest rclone and set custom location
try switch the mirror
