### ISSUE TITLE
Remote don't show folders

### ISSUE THREAD

**Issue by odacristo** [vKolerts/quest-sidenoder#9]
I updated to v0.2.2 but stay don't showing folders on click remote button.

Only show the "processing" message in center of window.

![image](https://user-images.githubusercontent.com/45353350/124294522-2de6a180-db2e-11eb-882a-92891256c979.png)

I'm using Windows 10.

**Comment by vKolerts** [comment]
Please try switch mirror at settings or download latest rclone and set custom location of exe file
